// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: dnsnx.proto

package nmsg_sie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DnsNX struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Qname            []byte  `protobuf:"bytes,1,req,name=qname" json:"qname,omitempty"`
	Qtype            *uint32 `protobuf:"varint,2,req,name=qtype" json:"qtype,omitempty"`
	Qclass           *uint32 `protobuf:"varint,3,req,name=qclass" json:"qclass,omitempty"`
	ResponseIp       []byte  `protobuf:"bytes,4,req,name=response_ip,json=responseIp" json:"response_ip,omitempty"`
	SoaRrname        []byte  `protobuf:"bytes,5,opt,name=soa_rrname,json=soaRrname" json:"soa_rrname,omitempty"`
	ResponseTimeSec  *int64  `protobuf:"varint,6,opt,name=response_time_sec,json=responseTimeSec" json:"response_time_sec,omitempty"`
	ResponseTimeNsec *int32  `protobuf:"fixed32,7,opt,name=response_time_nsec,json=responseTimeNsec" json:"response_time_nsec,omitempty"`
}

func (x *DnsNX) Reset() {
	*x = DnsNX{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dnsnx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DnsNX) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsNX) ProtoMessage() {}

func (x *DnsNX) ProtoReflect() protoreflect.Message {
	mi := &file_dnsnx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsNX.ProtoReflect.Descriptor instead.
func (*DnsNX) Descriptor() ([]byte, []int) {
	return file_dnsnx_proto_rawDescGZIP(), []int{0}
}

func (x *DnsNX) GetQname() []byte {
	if x != nil {
		return x.Qname
	}
	return nil
}

func (x *DnsNX) GetQtype() uint32 {
	if x != nil && x.Qtype != nil {
		return *x.Qtype
	}
	return 0
}

func (x *DnsNX) GetQclass() uint32 {
	if x != nil && x.Qclass != nil {
		return *x.Qclass
	}
	return 0
}

func (x *DnsNX) GetResponseIp() []byte {
	if x != nil {
		return x.ResponseIp
	}
	return nil
}

func (x *DnsNX) GetSoaRrname() []byte {
	if x != nil {
		return x.SoaRrname
	}
	return nil
}

func (x *DnsNX) GetResponseTimeSec() int64 {
	if x != nil && x.ResponseTimeSec != nil {
		return *x.ResponseTimeSec
	}
	return 0
}

func (x *DnsNX) GetResponseTimeNsec() int32 {
	if x != nil && x.ResponseTimeNsec != nil {
		return *x.ResponseTimeNsec
	}
	return 0
}

var File_dnsnx_proto protoreflect.FileDescriptor

var file_dnsnx_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x64, 0x6e, 0x73, 0x6e, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6e,
	0x6d, 0x73, 0x67, 0x2e, 0x73, 0x69, 0x65, 0x22, 0xe5, 0x01, 0x0a, 0x05, 0x44, 0x6e, 0x73, 0x4e,
	0x58, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c,
	0x52, 0x05, 0x71, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x05, 0x71, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x71, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06, 0x71,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x69, 0x70, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x49, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x61, 0x5f, 0x72, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x6f, 0x61, 0x52,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65,
	0x63, 0x12, 0x2c, 0x0a, 0x12, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x5f, 0x6e, 0x73, 0x65, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0f, 0x52, 0x10, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x4e, 0x73, 0x65, 0x63, 0x42,
	0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61,
	0x72, 0x73, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x63, 0x2f, 0x67, 0x6f, 0x2d, 0x6e, 0x6d, 0x73,
	0x67, 0x5f, 0x73, 0x69, 0x65, 0x3b, 0x6e, 0x6d, 0x73, 0x67, 0x5f, 0x73, 0x69, 0x65,
}

var (
	file_dnsnx_proto_rawDescOnce sync.Once
	file_dnsnx_proto_rawDescData = file_dnsnx_proto_rawDesc
)

func file_dnsnx_proto_rawDescGZIP() []byte {
	file_dnsnx_proto_rawDescOnce.Do(func() {
		file_dnsnx_proto_rawDescData = protoimpl.X.CompressGZIP(file_dnsnx_proto_rawDescData)
	})
	return file_dnsnx_proto_rawDescData
}

var file_dnsnx_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dnsnx_proto_goTypes = []interface{}{
	(*DnsNX)(nil), // 0: nmsg.sie.DnsNX
}
var file_dnsnx_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dnsnx_proto_init() }
func file_dnsnx_proto_init() {
	if File_dnsnx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dnsnx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DnsNX); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dnsnx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dnsnx_proto_goTypes,
		DependencyIndexes: file_dnsnx_proto_depIdxs,
		MessageInfos:      file_dnsnx_proto_msgTypes,
	}.Build()
	File_dnsnx_proto = out.File
	file_dnsnx_proto_rawDesc = nil
	file_dnsnx_proto_goTypes = nil
	file_dnsnx_proto_depIdxs = nil
}
