// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: qr.proto

package nmsg_sie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QRType int32

const (
	QRType_QUERY        QRType = 0
	QRType_RESPONSE     QRType = 1
	QRType_RESPONSE_END QRType = 2
	QRType_ERROR        QRType = 3
)

// Enum value maps for QRType.
var (
	QRType_name = map[int32]string{
		0: "QUERY",
		1: "RESPONSE",
		2: "RESPONSE_END",
		3: "ERROR",
	}
	QRType_value = map[string]int32{
		"QUERY":        0,
		"RESPONSE":     1,
		"RESPONSE_END": 2,
		"ERROR":        3,
	}
)

func (x QRType) Enum() *QRType {
	p := new(QRType)
	*p = x
	return p
}

func (x QRType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QRType) Descriptor() protoreflect.EnumDescriptor {
	return file_qr_proto_enumTypes[0].Descriptor()
}

func (QRType) Type() protoreflect.EnumType {
	return &file_qr_proto_enumTypes[0]
}

func (x QRType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *QRType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = QRType(num)
	return nil
}

// Deprecated: Use QRType.Descriptor instead.
func (QRType) EnumDescriptor() ([]byte, []int) {
	return file_qr_proto_rawDescGZIP(), []int{0}
}

type QR struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type          *QRType `protobuf:"varint,1,req,name=type,enum=nmsg.sie.QRType" json:"type,omitempty"`
	Text          []byte  `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	NumResponse   *uint32 `protobuf:"varint,3,opt,name=num_response,json=numResponse" json:"num_response,omitempty"`
	MoreAvailable *uint32 `protobuf:"varint,4,opt,name=more_available,json=moreAvailable" json:"more_available,omitempty"`
}

func (x *QR) Reset() {
	*x = QR{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QR) ProtoMessage() {}

func (x *QR) ProtoReflect() protoreflect.Message {
	mi := &file_qr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QR.ProtoReflect.Descriptor instead.
func (*QR) Descriptor() ([]byte, []int) {
	return file_qr_proto_rawDescGZIP(), []int{0}
}

func (x *QR) GetType() QRType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return QRType_QUERY
}

func (x *QR) GetText() []byte {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *QR) GetNumResponse() uint32 {
	if x != nil && x.NumResponse != nil {
		return *x.NumResponse
	}
	return 0
}

func (x *QR) GetMoreAvailable() uint32 {
	if x != nil && x.MoreAvailable != nil {
		return *x.MoreAvailable
	}
	return 0
}

var File_qr_proto protoreflect.FileDescriptor

var file_qr_proto_rawDesc = []byte{
	0x0a, 0x08, 0x71, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6e, 0x6d, 0x73, 0x67,
	0x2e, 0x73, 0x69, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x02, 0x51, 0x52, 0x12, 0x24, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6e, 0x6d, 0x73, 0x67,
	0x2e, 0x73, 0x69, 0x65, 0x2e, 0x51, 0x52, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6e, 0x75, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6d, 0x6f, 0x72, 0x65,
	0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0d, 0x6d, 0x6f, 0x72, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x2a,
	0x3e, 0x0a, 0x06, 0x51, 0x52, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x51, 0x55, 0x45,
	0x52, 0x59, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45,
	0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x45,
	0x4e, 0x44, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x42,
	0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61,
	0x72, 0x73, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x63, 0x2f, 0x67, 0x6f, 0x2d, 0x6e, 0x6d, 0x73,
	0x67, 0x5f, 0x73, 0x69, 0x65, 0x3b, 0x6e, 0x6d, 0x73, 0x67, 0x5f, 0x73, 0x69, 0x65,
}

var (
	file_qr_proto_rawDescOnce sync.Once
	file_qr_proto_rawDescData = file_qr_proto_rawDesc
)

func file_qr_proto_rawDescGZIP() []byte {
	file_qr_proto_rawDescOnce.Do(func() {
		file_qr_proto_rawDescData = protoimpl.X.CompressGZIP(file_qr_proto_rawDescData)
	})
	return file_qr_proto_rawDescData
}

var file_qr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_qr_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_qr_proto_goTypes = []interface{}{
	(QRType)(0), // 0: nmsg.sie.QRType
	(*QR)(nil),  // 1: nmsg.sie.QR
}
var file_qr_proto_depIdxs = []int32{
	0, // 0: nmsg.sie.QR.type:type_name -> nmsg.sie.QRType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_qr_proto_init() }
func file_qr_proto_init() {
	if File_qr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_qr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QR); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qr_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qr_proto_goTypes,
		DependencyIndexes: file_qr_proto_depIdxs,
		EnumInfos:         file_qr_proto_enumTypes,
		MessageInfos:      file_qr_proto_msgTypes,
	}.Build()
	File_qr_proto = out.File
	file_qr_proto_rawDesc = nil
	file_qr_proto_goTypes = nil
	file_qr_proto_depIdxs = nil
}
