// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: reputation.proto

package nmsg_sie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReputationType int32

const (
	ReputationType_ADDRESS    ReputationType = 0
	ReputationType_HOST       ReputationType = 1
	ReputationType_DOMAIN     ReputationType = 2
	ReputationType_NAMESERVER ReputationType = 3
	ReputationType_URI        ReputationType = 4
)

// Enum value maps for ReputationType.
var (
	ReputationType_name = map[int32]string{
		0: "ADDRESS",
		1: "HOST",
		2: "DOMAIN",
		3: "NAMESERVER",
		4: "URI",
	}
	ReputationType_value = map[string]int32{
		"ADDRESS":    0,
		"HOST":       1,
		"DOMAIN":     2,
		"NAMESERVER": 3,
		"URI":        4,
	}
)

func (x ReputationType) Enum() *ReputationType {
	p := new(ReputationType)
	*p = x
	return p
}

func (x ReputationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReputationType) Descriptor() protoreflect.EnumDescriptor {
	return file_reputation_proto_enumTypes[0].Descriptor()
}

func (ReputationType) Type() protoreflect.EnumType {
	return &file_reputation_proto_enumTypes[0]
}

func (x ReputationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ReputationType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ReputationType(num)
	return nil
}

// Deprecated: Use ReputationType.Descriptor instead.
func (ReputationType) EnumDescriptor() ([]byte, []int) {
	return file_reputation_proto_rawDescGZIP(), []int{0}
}

type Reputation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       *ReputationType `protobuf:"varint,1,req,name=type,enum=nmsg.sie.ReputationType" json:"type,omitempty"`
	Tag        []byte          `protobuf:"bytes,2,req,name=tag" json:"tag,omitempty"`
	Value      []byte          `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	Address    []byte          `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	Netmask    []byte          `protobuf:"bytes,5,opt,name=netmask" json:"netmask,omitempty"`
	Host       []byte          `protobuf:"bytes,6,opt,name=host" json:"host,omitempty"`
	Domain     []byte          `protobuf:"bytes,7,opt,name=domain" json:"domain,omitempty"`
	Nameserver []byte          `protobuf:"bytes,8,opt,name=nameserver" json:"nameserver,omitempty"`
	Uri        []byte          `protobuf:"bytes,9,opt,name=uri" json:"uri,omitempty"`
	Port       *uint32         `protobuf:"varint,10,opt,name=port" json:"port,omitempty"`
}

func (x *Reputation) Reset() {
	*x = Reputation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reputation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reputation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reputation) ProtoMessage() {}

func (x *Reputation) ProtoReflect() protoreflect.Message {
	mi := &file_reputation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reputation.ProtoReflect.Descriptor instead.
func (*Reputation) Descriptor() ([]byte, []int) {
	return file_reputation_proto_rawDescGZIP(), []int{0}
}

func (x *Reputation) GetType() ReputationType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ReputationType_ADDRESS
}

func (x *Reputation) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *Reputation) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Reputation) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Reputation) GetNetmask() []byte {
	if x != nil {
		return x.Netmask
	}
	return nil
}

func (x *Reputation) GetHost() []byte {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Reputation) GetDomain() []byte {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *Reputation) GetNameserver() []byte {
	if x != nil {
		return x.Nameserver
	}
	return nil
}

func (x *Reputation) GetUri() []byte {
	if x != nil {
		return x.Uri
	}
	return nil
}

func (x *Reputation) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

var File_reputation_proto protoreflect.FileDescriptor

var file_reputation_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x65, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x6e, 0x6d, 0x73, 0x67, 0x2e, 0x73, 0x69, 0x65, 0x22, 0x88, 0x02, 0x0a,
	0x0a, 0x52, 0x65, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6e, 0x6d, 0x73, 0x67,
	0x2e, 0x73, 0x69, 0x65, 0x2e, 0x52, 0x65, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6e,
	0x65, 0x74, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6e, 0x65,
	0x74, 0x6d, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x75, 0x72, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x2a, 0x4c, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x75, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x44, 0x44,
	0x52, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x4f, 0x53, 0x54, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x44, 0x4f, 0x4d, 0x41, 0x49, 0x4e, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a,
	0x4e, 0x41, 0x4d, 0x45, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03,
	0x55, 0x52, 0x49, 0x10, 0x04, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61, 0x72, 0x73, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x63, 0x2f,
	0x67, 0x6f, 0x2d, 0x6e, 0x6d, 0x73, 0x67, 0x5f, 0x73, 0x69, 0x65, 0x3b, 0x6e, 0x6d, 0x73, 0x67,
	0x5f, 0x73, 0x69, 0x65,
}

var (
	file_reputation_proto_rawDescOnce sync.Once
	file_reputation_proto_rawDescData = file_reputation_proto_rawDesc
)

func file_reputation_proto_rawDescGZIP() []byte {
	file_reputation_proto_rawDescOnce.Do(func() {
		file_reputation_proto_rawDescData = protoimpl.X.CompressGZIP(file_reputation_proto_rawDescData)
	})
	return file_reputation_proto_rawDescData
}

var file_reputation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_reputation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_reputation_proto_goTypes = []interface{}{
	(ReputationType)(0), // 0: nmsg.sie.ReputationType
	(*Reputation)(nil),  // 1: nmsg.sie.Reputation
}
var file_reputation_proto_depIdxs = []int32{
	0, // 0: nmsg.sie.Reputation.type:type_name -> nmsg.sie.ReputationType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reputation_proto_init() }
func file_reputation_proto_init() {
	if File_reputation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reputation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reputation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reputation_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reputation_proto_goTypes,
		DependencyIndexes: file_reputation_proto_depIdxs,
		EnumInfos:         file_reputation_proto_enumTypes,
		MessageInfos:      file_reputation_proto_msgTypes,
	}.Build()
	File_reputation_proto = out.File
	file_reputation_proto_rawDesc = nil
	file_reputation_proto_goTypes = nil
	file_reputation_proto_depIdxs = nil
}
