usr/share/gocode/src/github.com/farsightsec/go-nmsg-sie/delay.pb.go
usr/share/gocode/src/github.com/farsightsec/go-nmsg-sie/dnsdedupe.pb.go
usr/share/gocode/src/github.com/farsightsec/go-nmsg-sie/dnsnx.pb.go
usr/share/gocode/src/github.com/farsightsec/go-nmsg-sie/newdomain.pb.go
usr/share/gocode/src/github.com/farsightsec/go-nmsg-sie/qr.pb.go
usr/share/gocode/src/github.com/farsightsec/go-nmsg-sie/reputation.pb.go
usr/share/gocode/src/github.com/farsightsec/go-nmsg-sie/sie.go
