usr/share/gocode/src/github.com/farsightsec/go-nmsg_sie/delay.pb.go
usr/share/gocode/src/github.com/farsightsec/go-nmsg_sie/dnsdedupe.pb.go
usr/share/gocode/src/github.com/farsightsec/go-nmsg_sie/dnsnx.pb.go
usr/share/gocode/src/github.com/farsightsec/go-nmsg_sie/newdomain.pb.go
usr/share/gocode/src/github.com/farsightsec/go-nmsg_sie/qr.pb.go
usr/share/gocode/src/github.com/farsightsec/go-nmsg_sie/reputation.pb.go
usr/share/gocode/src/github.com/farsightsec/go-nmsg_sie/sie.go
